#!/bin/bash
# This file will be sourced by the scripts automatically

### /etc/makepkg.conf
#PKGEXT=".pkg.tar.xz"
#COMPRESSXZ=(xz -c -z - --threads=0)
#PACKAGER="Killer-Hacker-Oficial <Telegram: @Killer_Hacker_Oficial>"
#GPGKEY="C8454045DA87F259D9D84D58BBD2787BEF5F46ED"

REPONAME="ctlos_dev"
CTLOS="creio@storage.osdn.net:/storage/groups/c/ct/ctlos/Repo" # supports ssh config aliases
